[package]
name = "gadio-rss"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rss = "1.0"
html5ever = "0.25.1"
reqwest = "0.11.4"